### ISSUE TITLE
 Property 'fromEvent' does not exist on type 'typeof Observable'.

### ISSUE THREAD

**Issue by throne1986** [stokingerl/ng2-sticky-nav#7]
I want to create a sticky nav in angular 6 but unfortunatelly does not work

Here is is error I am getting `ERROR in node_modules/ng2-sticky-nav/src/sticky-nav.directive.ts(21,20): error TS2339: Property 'fromEvent' does not exist on type 'typeof Observable'.`

can you please update the package for angular 6 users?

**Comment by willyboy** [comment]
Updated.
